project:
  type: website
  output-dir: docs

website:
  title: "Chi's Blog"
  navbar:
    right:
      - about.qmd
      - icon: github
        href: https://github.com/codescv
      - icon: twitter
        href: https://twitter.com/codescv
format:
  html:
    theme: cosmo
    css: styles.css



